[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1"
aoc = { path = "src/aoc" }

[dev-dependencies]
criterion = "*"

[[bench]]
name = "aoc2023"
harness = false

[profile.release]
debug = true